import base64

# Simple 16x16 PNG (gradient blue square)
icon16_b64 = """
iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA7UlEQVR42mNkoBAwMiABRgYGBmZGFhZuBgkJSY
BJkZmJhZ2FgZ2PlZONhQGIhQGIhRkZmZm4GVi4Odi5uXlAABBBBZCtQhYCbQaoaQCsQoAbgFDFxsLLy8HKx8
fPwMjMxMbKwM7Dy8HLw8vMwMwCqLrKISBGI+To4uTmAWJ+SjaOTk5uNgZQNIxTlYmJkY2fg5OLo5QPi5QAEE
EBsXYYhLQPWchDs/v//6+puZmZmZmRkZGRnZGBgY2VgZQPyfyiCxKEpnsf//Z2RgYGRgZGBkYGRgZGBkYARsB
gYGBgYGRkZGBkQEA9x1VwL3FDyoAAAAASUVORK5CYII=
"""

# 48x48 PNG 
icon48_b64 = """
iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA4klEQVRoge2YOw6AIBAEn0X9/1/deOyBiYVY
GJKm5Jx7trPZ7AaMMUYJQAJQ+6wAkQEiA0QGyACRAaIDRAaIDJAZIDJA5L8OsAEyQGSAyACRAaIDRAaIDJAZ
IDJA/+1nB9gAkQEiA0QGiAwQGSByvx1gA0QGiAwQGSBb+7ADbIDIAJEBIgNEBogMEBkgMkBkgMh+3AEGyACR
ASIDRAaIDJAZIDJAVIDsPvuBAxogMkBkgMgAkQEiA0QGiAzQ+7MDbIDIAJEBIgNEBogMEBkgMkBkgOzDDrAB
IgNEBogMEBkgMkBkgMgAkQHK/+4ABogMEBkgMkBkgMgAkQEiA0QGyACRASID5H93gAESARJgAEw/rdkZjtue
AAAAAElFTkSuQmCC
"""

# 128x128 PNG
icon128_b64 = """
iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAA0klEQVR4nO3PMQ0AAAjAMA7B/kHGHh4JIbQn
JffhLgABiAQQCyAWQCwAWICwAOCf6G0GBLAAYQHAvwABAQwIGEBAAAICAxgQMAAAAgIYEDCAgAAEBgAwIGAA
AQEMCBhAQAAAggIYEDCAgAAEBAAwIGAAAQEMCBhgQAAAggIYEDDAgAAABAQwIGAAAQEMCBhgQAAAggIYEDDA
gAABAgYYEAAAAgIYEDDAgAAAASIABAAQEMAABAgYYAAAAAQEMAAAAAgIYAAAAAQEMAAAAAgIYAAAAAQEMAAAA
AgIYAAAAAQEMAAAAAgIYAAAAAQEMAAAAAv8a7gABJtVjPwAAAABJRU5ErkJggg==
"""

def create_png(filename, b64_data):
    data = base64.b64decode(b64_data.strip())
    with open(filename, 'wb') as f:
        f.write(data)
    print(f"Created {filename}")

create_png("icon16.png", icon16_b64)
create_png("icon48.png", icon48_b64)
create_png("icon128.png", icon128_b64)
print("Done!")
